### ISSUE TITLE
https reports bad cert

### ISSUE THREAD

**Issue by ghost** [onevotepercitizen/ijustwantedtovote.today#12]
Minor - For anyone who is worried about reporting issues through a tool and tries to connect using https, they will get a mismatch error for the certificate (hosted by github). This may make people reluctant to use the service.

**Comment by colindean** [comment]
As in, https://ijustwantedtovote.today?

I can't really do much about it :-/

I'd **love** to use https://onevotepercitizen.github.io/ijustwantedtovote.today but Github Pages redirects to http://ijustwantedtovote.today 👎
