### ISSUE TITLE
Address field naming

### ISSUE THREAD

**Issue by mfulgo** [onevotepercitizen/ijustwantedtovote.today#8]
In Chrome, auto complete in the address field only fills in the first two lines of my address. You can probably tweak the field name to better match full-address fields. (Or split it up into multiple fields.)

**Comment by colindean** [comment]
Should it be `full-address`?

**Comment by colindean** [comment]
Looks like whatwg says `street-address`: https://wiki.whatwg.org/wiki/Autocomplete_Types

I don't really want to break it into separate fields :-/
